services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 80:80
      - 443:443 #for future ssl traffic

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=learn_php
      - MYSQL_USER=learn_php
      - MYSQL_PASSWORD=password # this should live in and env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #
    #volumes:
    #  - "./db:/docker-entrypoint-initdb.d" # initialize db with data
    # must run in terminal: docker-php-ext-install mysqli
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306